"""
Command-line interface for running Monte Carlo simulations.

This script allows users to run simulations from the command line using a
pre-generated config.yaml file. It satisfies FR4.1 requirement:
"The engine shall run from the command line and be configured via a config.yaml file."

Usage:
    python simulate.py config.yaml
    python simulate.py path/to/config.yaml
    python simulate.py --help

The script will:
1. Load the configuration from the specified YAML file
2. Load random seeds from seeds.txt (if configured)
3. Execute the Monte Carlo simulation
4. Write results to data/outputs/summary_stats.csv and data/outputs/raw_positions.csv
"""

from __future__ import annotations

import logging
import sys
from argparse import ArgumentParser
from pathlib import Path

from src.monte_carlo.monte_carlo import run_simulation


def setup_logging(verbose: bool = False) -> logging.Logger:
    """
    Configure logging for console output.

    Args:
        verbose: If True, show DEBUG level logs. Otherwise show INFO level.
    """
    log_level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=log_level,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Initialize logging
    logger = logging.getLogger(__name__)

    return logger


def main():
    """
    Main entry point for the CLI.
    """
    parser = ArgumentParser(
        description="Run Monte Carlo simulation from command line using a config.yaml file",
        epilog="Example: python simulate.py config.yaml",
    )

    parser.add_argument(
        "config",
        type=Path,
        help="Path to the config.yaml file (generated by the GUI or manually created)",
    )

    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="Output directory for results (default: data/outputs)",
    )

    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable verbose logging (DEBUG level)",
    )

    args = parser.parse_args()

    # Run simulation and exit with status code
    logger = setup_logging(args.verbose)
    logger.info(f"Running simulation with config: {args.config}")

    exit_code = run_simulation(args.config, args.output, args.verbose)

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
